config/routes.rb
Rails.application.routes.draw do
    resources :products
    root 'products#index'
    root 'top#main'
    get 'top/main'
    resources :cart_items, only: [:new, :create, :destroy]
    resources :carts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
    has_one :cart_item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_cart
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
    helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    def new
        @cart_item = CartItem.new
    end
    def create
        logger.debug "---------------"
        cart = Cart.find_by(id: current_cart.id)
        @cart_item =CartItem.new(qty: params[:cart_item][:qty], cart_id: cart.id)
        if @cart_item.save
            flash[:notice] = 'カートに追加しました'
            redirect_to cart_path
        else 
            render new_cart_item_path
        end
    end
    def destroy
        cart_item = CartItem.find(params[:id])
        if cart_item.destroy
            flash[:notice] = "カートから削除しました"
        end
        redirect_to root_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @cart = Cart.all
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end
    def new
        @product = Product.new
    end
    def create
        logger.debug "---------------"
        @product = Product.new(name: params[:product][:name], 
        price: params[:product][:price])
        if @product.save
            flash[:notice] = '商品を登録しました'
            redirect_to root_path
        else 
            render new_product_path
        end
    end
    def destroy
        product = Product.find(params[:id])
        if product.destroy
            flash[:notice] = "商品を削除しました"
        end
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        redirect_to products_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/new.html.erb
<%= form_for @cart_item, url: {action: :create} do |f| %>
  <p><%= f.label :name, '商品名：' %><%= params[:name] %></p>
  <p><%= f.label :price, '価格：' %><%= params[:price] %></p>
  <%= f.hidden_field :product_id, :product_id => @cart_item.product_id %>
    <p><%= f.label :qty, '数量' %>
    <%= f.text_field :qty %></p>
    <%= f.submit '登録' %>
<% end %>

app/views/carts/show.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<% @cart.each do |e| %>
    <% @sum = 0 %>
        <p>商品名：</p>
        <p>価格：</p>
        <p>数量：</p>
        <%= link_to 'カートから削除する',cart_items_path(e) , method: :delete %>
<% end %>

<p>合計金額：<%= @sum %>円</p>

<p><%= link_to '商品一覧ページ', root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>
<% @products.each do |e| %>
  <p>
    <%= e.name %>
    <%= e.price %>円
    <%= link_to '削除', product_path(e), method: :delete %>
    <%= link_to 'カートに入れる', new_cart_item_path(product_id: e.id) %>
  </p>
<% end %>

<p><%= link_to '商品を新規登録する', new_product_path %></p>
<p><%= link_to 'カートを見る', '/carts/show' %></p>

app/views/products/new.html.erb
<% if @product.errors.present? %>
<h3>エラーがあります</h3>
<ul>
  <% @product.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<%= form_for @product, url: {action: :create} do |f| %>
  <%= f.label :name, '商品名' %> 
  <%= f.text_field :name %>
  <%= f.label :price, '価格' %> 
  <%= f.text_field :price %>円
  <%= f.submit '登録' %>
<% end %>